version: '3.8'

services:

  fastapi:
    container_name: backend 
    build: ./backend
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
    ports:
      - '8000:8000'
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/ogtsync
    depends_on:
      - db

  #react : 
  #  container_name: frontend
  #  build: ./frontend 
  #  volumes:
  #    - ./frontend:/app
  #  ports : 
  #    - '3000:3000'
  #  depends_on:
  #    - fastapi
  #  stdin_open: true
  #  tty: true

  db:
    image: postgres:13.4
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ogtsync
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - db