"""add news tables

Revision ID: 7ffad02dca95
Revises: 
Create Date: 2022-05-18 18:50:59.307673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ffad02dca95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fonctions',
    sa.Column('datecreate', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dateupdate', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nature', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nature')
    )
    op.create_table('users',
    sa.Column('datecreate', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dateupdate', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('im', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('fonction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fonction_id'], ['fonctions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('ogts',
    sa.Column('datecreate', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dateupdate', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('intitule', sa.String(length=50), nullable=False),
    sa.Column('abrev', sa.String(length=50), nullable=True),
    sa.Column('niveau', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('userc_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userc_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abrev'),
    sa.UniqueConstraint('intitule')
    )
    op.create_table('versionogts',
    sa.Column('datecreate', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dateupdate', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('periode', sa.Integer(), nullable=False),
    sa.Column('typeogt', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('userc_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userc_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rubriques',
    sa.Column('datecreate', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dateupdate', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('intitule', sa.String(length=50), nullable=False),
    sa.Column('abrev', sa.String(length=50), nullable=True),
    sa.Column('niveau_saisi', sa.Integer(), nullable=True),
    sa.Column('niveau_sorti', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('fonction_id', sa.Integer(), nullable=False),
    sa.Column('ogt_id', sa.Integer(), nullable=False),
    sa.Column('userc_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fonction_id'], ['fonctions.id'], ),
    sa.ForeignKeyConstraint(['ogt_id'], ['ogts.id'], ),
    sa.ForeignKeyConstraint(['userc_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abrev'),
    sa.UniqueConstraint('intitule')
    )
    op.create_table('saisis',
    sa.Column('datecreate', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('montant', sa.Float(), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=False),
    sa.Column('rubrique_id', sa.Integer(), nullable=False),
    sa.Column('versionogt_id', sa.Integer(), nullable=False),
    sa.Column('userc_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rubrique_id'], ['rubriques.id'], ),
    sa.ForeignKeyConstraint(['userc_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['versionogt_id'], ['versionogts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suivisaisis',
    sa.Column('dateupdate', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('saisi_id', sa.Integer(), nullable=False),
    sa.Column('userc_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['saisi_id'], ['saisis.id'], ),
    sa.ForeignKeyConstraint(['userc_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('validations',
    sa.Column('datecreate', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_valide', sa.Boolean(), nullable=True),
    sa.Column('saisi_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['saisi_id'], ['saisis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suivivalidations',
    sa.Column('datecreate', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dateupdate', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('validation_id', sa.Integer(), nullable=False),
    sa.Column('userc_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userc_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['validation_id'], ['validations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suivivalidations')
    op.drop_table('validations')
    op.drop_table('suivisaisis')
    op.drop_table('saisis')
    op.drop_table('rubriques')
    op.drop_table('versionogts')
    op.drop_table('ogts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('fonctions')
    # ### end Alembic commands ###
